### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by Weffe** [YavorPaunov/deepstreampy#4]
Hello,

Came across this library when looking for python and deepstream and was wondering if this is mature enough to use in an application? Are all features implemented for records, pub/sub and rpcs? 

Thanks! Was just curious 😄

**Comment by alv000h** [comment]
+1

**Comment by jisaacstone** [comment]
We are using this in production and everything does work but it is a bit rough around the edges.

Had some random crashing, just put in a PR for what I believe to be the major culprit -> https://github.com/YavorPaunov/deepstreampy/pull/7

We are using records, pub/sub (publish only in this library) and rpcs

Main complaint is lack of documentation/examples, but the code is readable and works.
Second thing is the default error handling seems to be to crash. Adding an error handler (`client.on('error', handle_error)`) helps a lot.

So yeah if you need to get deepstream into an existing python codebase this will get the job done, but if you are starting from scratch use a language that has an official client library like nodejs. It is much easier to use and better documented.

**Comment by Weffe** [comment]
Thanks for the info. I have moved on from the project that was using deepstream but I'm sure this info might be helpful for other people in the future.

Closing for now.
